### ISSUE TITLE
Shifts Prisma Model

### ISSUE THREAD

**Issue by jstelnik** [ChrisWilhelm/MathForABetterWorld#5]
name, email, start, end, food taken

**Comment by i-api** [comment]
Forgot to mark this one as completed.

commit 9ea52b40909498f60ccd9a066ea2ba60d93f7134
Author: i-api <87678394+i-api@users.noreply.github.com>
Date:   Mon Feb 20 15:53:30 2023 -0500

    added Shift [Date: 02/20/2023] [Time: 15:53:30]
